            efficiently sub-resultant PRS.

            Assuming that M is a square matrix of dimension N x N and
            I is N x N identity matrix, then the Berkowitz vector is
            an N x 1 vector whose entries are coefficients of the
            polynomial

                           charpoly(M) = det(t*I - M)

            As a consequence, all polynomials generated by Berkowitz
            algorithm are monic.

           For more information on the implemented algorithm refer to:

           [1] S.J. Berkowitz, On computing the determinant in small
               parallel time using a small number of processors, ACM,
               Information Processing Letters 18, 1984, pp. 147-150

           [2] M. Keber, Division-Free computation of sub-resultants
               using Bezout matrices, Tech. Report MPI-I-2006-1-006,
               Saarbrucken, 2006
        """

        # handle the trivial cases
        if self.rows == 0 and self.cols == 0:
            return self._new(1, 1, [S.One])
        elif self.rows == 1 and self.cols == 1:
            return self._new(2, 1, [S.One, -self[0,0]])

        submat, toeplitz = self._eval_berkowitz_toeplitz_matrix()
        return toeplitz * submat._eval_berkowitz_vector()

    def _eval_det_bareiss(self):
        """Compute matrix determinant using Bareiss' fraction-free
        algorithm which is an extension of the well known Gaussian
        elimination method. This approach is best suited for dense
        symbolic matrices and will result in a determinant with
        minimal number of fractions. It means that less term
        rewriting is needed on resulting formulae.

        http://www.eecis.udel.edu/~saunders/papers/sffge/it5.ps.
        """

        # Recursively implemented Bareiss' algorithm as per Deanna Richelle Leggett's
        # thesis http://www.math.usm.edu/perry/Research/Thesis_DRL.pdf
        def bareiss(mat, cumm=1):
        def bareiss(mat, cumm=1):
            if mat.rows == 0:
                return S.One
            elif mat.rows == 1:
                return mat[0, 0]

            # find a pivot and extract the remaining matrix
            # XXX should use `_find_reasonable_pivot`.  Blocked by issue #12362
            pivot_pos, pivot_val, _, _ = _find_pivot(mat[:, 0])
            if pivot_pos == None:
                return S.Zero

            # if we have a valid pivot, we'll do a "row swap", so keep the
            # sign of the det
            sign = (-1) ** (pivot_pos % 2)

            # we want every row but the pivot row and every column
            rows = list(i for i in range(mat.rows) if i != pivot_pos)
            cols = list(range(mat.cols))
            tmp_mat = mat.extract(rows, cols)

            def entry(i, j):
                ret = (pivot_val*tmp_mat[i, j + 1] - mat[pivot_pos, j + 1]*tmp_mat[i, 0]) / cumm
                if not ret.is_Atom:
                    cancel(ret)
                return ret

            return sign*bareiss(self._new(mat.rows - 1, mat.cols - 1, entry), pivot_val)

        return cancel(bareiss(self))

    def _eval_det_berkowitz(self):
        """ Use the Berkowitz algorithm to compute the determinant."""
        berk_vector = self._eval_berkowitz_vector()
        return (-1)**(len(berk_vector) - 1) * berk_vector[-1]

    def _eval_det_lu(self, iszerofunc=_iszero, simpfunc=None):
        """ Computes the determinant of a matrix from its LU decomposition.
        This function uses the LU decomposition computed by
        LUDecomposition_Simple().
